services:
  mysql:
    image: mysql:8.0
    container_name: jelou-mysql
    environment:
      MYSQL_ROOT_PASSWORD: changeme
      MYSQL_DATABASE: jelou
    ports:
      - "3307:3306"
    volumes:
      - ./db/schema.sql:/docker-entrypoint-initdb.d/1-schema.sql:ro
      - ./db/seed.sql:/docker-entrypoint-initdb.d/2-seed.sql:ro
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-uroot", "-p$${MYSQL_ROOT_PASSWORD}"]
      interval: 5s
      timeout: 3s
      retries: 30
    networks:
      - jelou_net

  customers-api:
    build:
      context: ./customers-api
    container_name: customers-api
    env_file: ./customers-api/.env
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "3001:3001"
    networks:
      - jelou_net

  orders-api:
    build: ./orders-api
    container_name: orders-api
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: ${MYSQL_ROOT_PASSWORD:-changeme}
      DB_NAME: ${MYSQL_DATABASE:-store}
      JWT_SECRET: ${JWT_SECRET:-dev-secret}
      SERVICE_TOKEN: ${SERVICE_TOKEN:-service_token_dev}
      PORT: 3002
    ports:
      - "3002:3002"
    links:
      - mysql

networks:
  jelou_net:
    driver: bridge
