service: lambda-orchestrator
useDotenv: true

provider:
  name: aws
  runtime: nodejs16.x
  environment:
    CUSTOMERS_API_BASE: ${env:CUSTOMERS_API_BASE, 'http://localhost:3001'}
    ORDERS_API_BASE:    ${env:ORDERS_API_BASE,    'http://localhost:3002'}
    SERVICE_TOKEN:      ${env:SERVICE_TOKEN,      'service-secret-123'}

plugins:
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 3000
    lambdaPort: 3005
    noPrependStageInUrl: true

functions:
  createAndConfirmOrder:
    handler: src/handler.createAndConfirmOrder
    events:
      - httpApi:
          method: POST
          path: /orchestrator/create-and-confirm-order