CREATE DATABASE IF NOT EXISTS jelou CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE jelou;


--Clientes
CREATE TABLE IF NOT EXISTS customers (
id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
name VARCHAR(150) NOT NULL,
email VARCHAR(180) NOT NULL UNIQUE,
phone VARCHAR(50) NULL,
created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
deleted_at TIMESTAMP NULL DEFAULT NULL
) ENGINE=InnoDB;


--Productos
CREATE TABLE IF NOT EXISTS products (
id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
sku VARCHAR(100) NOT NULL UNIQUE,
name VARCHAR(200) NOT NULL,
price_cents BIGINT NOT NULL,
stock INT NOT NULL DEFAULT 0,
created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;


--Órdenes
CREATE TABLE IF NOT EXISTS orders (
id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
customer_id BIGINT UNSIGNED NOT NULL,
status ENUM('CREATED','CONFIRMED','CANCELED') NOT NULL,
total_cents BIGINT NOT NULL DEFAULT 0,
created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
CONSTRAINT fk_orders_customer FOREIGN KEY (customer_id) REFERENCES customers(id)
ON UPDATE CASCADE ON DELETE RESTRICT
) ENGINE=InnoDB;


--Items de la orden
CREATE TABLE IF NOT EXISTS order_items (
id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
order_id BIGINT UNSIGNED NOT NULL,
product_id BIGINT UNSIGNED NOT NULL,
qty INT NOT NULL,
unit_price_cents BIGINT NOT NULL,
subtotal_cents BIGINT NOT NULL,
CONSTRAINT fk_order_items_order FOREIGN KEY (order_id) REFERENCES orders(id)
ON UPDATE CASCADE ON DELETE CASCADE,
CONSTRAINT fk_order_items_product FOREIGN KEY (product_id) REFERENCES products(id)
ON UPDATE CASCADE ON DELETE RESTRICT
) ENGINE=InnoDB;


--Idempotencia confirmación de órdenes
CREATE TABLE IF NOT EXISTS idempotency_keys (
`key` VARCHAR(128) NOT NULL,
target_type ENUM('ORDER_CONFIRM') NOT NULL,
target_id BIGINT UNSIGNED NOT NULL,
status ENUM('PENDING','SUCCEEDED','FAILED') NOT NULL DEFAULT 'PENDING',
response_body JSON NULL,
created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
expires_at TIMESTAMP NULL DEFAULT NULL,
PRIMARY KEY (`key`),
KEY idx_idem_target (target_type, target_id)
) ENGINE=InnoDB;