openapi: 3.0.3
info:
  title: Customers API
  version: "1.0.0"
servers:
  - url: http://localhost:3001
paths:
  /health:
    get:
      summary: Salud del servicio
      responses:
        "200":
          description: OK
          content:
            application/json:
              example: { ok: true, service: "customers-api" }
  /internal/customers/{id}:
    get:
      summary: Detalle interno de cliente (requiere token de servicio)
      parameters:
        - in: path
          name: id
          required: true
          schema: { type: integer }
      security:
        - ServiceTokenAuth: []
      responses:
        "200":
          description: Cliente
          content:
            application/json:
              schema: { $ref: "#/components/schemas/Customer" }
              example: { id: 1, name: "Demo", email: "ops@acme.com", phone: "+57 300 000 0000", created_at: "2025-10-25T13:23:19.000Z" }
        "401":
          description: No autorizado
          content:
            application/json:
              example: { error: "unauthorized" }
        "404":
          description: No encontrado
          content:
            application/json:
              example: { error: "not_found" }
components:
  securitySchemes:
    ServiceTokenAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    Customer:
      type: object
      properties:
        id: { type: integer }
        name: { type: string }
        email: { type: string }
        phone: { type: string }
        created_at: { type: string, format: date-time }
